# render.yaml
services:
  - name: flask-backend
    type: web
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    ports:
      - port: 5000
        protocol: HTTP

  - name: nextjs-frontend
    type: web
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: http://flask-backend:5000
    ports:
      - port: 3000
        protocol: HTTP
    dependsOn:
      - flask-backend
